variables:
  REGISTRY: "docker-hub.2gis.ru"

stages:
  - build
  - report
  - dockerize
  - deploy
  - end

before_script:
  - export CI_TAG=`[[ -z ${CI_COMMIT_TAG} ]] && echo "branch-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA:0:8}" || echo "${CI_COMMIT_TAG}"`

# ================= Test & Build =================

build:app:
  image: $REGISTRY/microsoft/dotnet:2.2.105-sdk-alpine3.9
  stage: build
  when: always
  script:
    - dotnet restore --runtime alpine.3.9-x64
    - dotnet test tests/VStore.UnitTests/VStore.UnitTests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput="`pwd`/coverage/"
    - dotnet publish src/VStore.Host --configuration Release --runtime alpine.3.9-x64 --output ../../publish/vstore
    - dotnet publish src/VStore.Worker --configuration Release --runtime alpine.3.9-x64 --output ../../publish/vstore-worker
    - dotnet publish src/VStore.Renderer --configuration Release --runtime alpine.3.9-x64 --output ../../publish/vstore-renderer
    - cp lib/librdkafka-0.11.6-alpine.3.9-ssl-lz4.so publish/vstore/librdkafka.so
    - cp lib/librdkafka-0.11.6-alpine.3.9-ssl-lz4.so publish/vstore-worker/librdkafka.so
  tags: [ 2gis, docker ]
  artifacts:
    name: "${CI_COMMIT_REF_NAME}_app"
    expire_in: '1 week'
    paths:
      - coverage/
      - publish/vstore/
      - publish/vstore-worker/
      - publish/vstore-renderer/

build:cloning-tool:
  image: $REGISTRY/microsoft/dotnet:2.2.105-sdk-alpine3.9
  stage: build
  when: manual
  script:
    - dotnet publish src/CloningTool --configuration Release --runtime alpine.3.9-x64 --output ../../publish/cloning-tool
  tags: [ 2gis, docker ]
  artifacts:
    name: "${CI_COMMIT_REF_NAME}_cloning_tool"
    expire_in: '1 week'
    paths:
      - publish/cloning-tool/

generate:coverage:
  image: $REGISTRY/2gis/alpine:3.7-lcov
  stage: report
  allow_failure: true
  script:
    - genhtml coverage/coverage.info --quiet --output-directory coverage_report
  dependencies:
    - build:app
  tags: [ 2gis, docker ]
  artifacts:
    name: "${CI_COMMIT_REF_NAME}_coverage_report"
    expire_in: '1 week'
    paths:
      - coverage_report/

build:vstore-host-image:
  stage: dockerize
  when: manual
  allow_failure: false
  script:
    - export IMAGE_TAG=$REGISTRY/ams/vstore:${CI_TAG}
    - docker build --pull --rm --tag $IMAGE_TAG -f publish/vstore/Dockerfile publish/vstore
    - docker push $IMAGE_TAG
  tags: [ docker-engine, io ]
  dependencies:
    - build:app

build:vstore-worker-image:
  stage: dockerize
  when: manual
  allow_failure: false
  script:
    - export IMAGE_TAG=$REGISTRY/ams/vstore-worker:${CI_TAG}
    - docker build --pull --rm --tag $IMAGE_TAG -f publish/vstore-worker/Dockerfile publish/vstore-worker
    - docker push $IMAGE_TAG
  tags: [ docker-engine, io ]
  dependencies:
    - build:app
    
build:vstore-renderer-image:
  stage: dockerize
  when: manual
  allow_failure: false
  script:
    - export IMAGE_TAG=$REGISTRY/ams/vstore-renderer:${CI_TAG}
    - docker build --pull --rm --tag $IMAGE_TAG -f publish/vstore-renderer/Dockerfile publish/vstore-renderer
    - docker push $IMAGE_TAG
  tags: [ docker-engine, io ]
  dependencies:
    - build:app

build:cloning-tool-image:
  stage: dockerize
  when: manual
  script:
    - export IMAGE_TAG=$REGISTRY/ams/cloning-tool:${CI_TAG}
    - docker build --pull --rm --tag $IMAGE_TAG -f publish/cloning-tool/Dockerfile publish/cloning-tool
    - docker push $IMAGE_TAG
  tags: [ docker-engine, io ]
  dependencies:
    - build:cloning-tool

# ================ Deploy =================

deploy:standalone:
  stage: deploy
  when: manual
  image: $REGISTRY/2gis-io/k8s-handle:latest
  script:
    - export VSTORE_ENVIRONMENT=Stage
    - k8s-handle deploy --config config-standalone.yaml --section vstore --sync-mode True
  only:
    - tags
  dependencies: []
  tags: [ 2gis, docker ]
  environment:
    name: vstore-standalone
    url: http://${CI_ENVIRONMENT_SLUG}.web-staging.2gis.ru/swagger

deploy:relizard:
  stage: deploy
  environment:
    name: staging
    url: http://vstore-stage.web-staging.2gis.ru/swagger
  only:
    - tags
  script:
    - "curl -X POST -F token=${AMS_DEPLOY_TRIGGER_TOKEN} -F ref=master https://gitlab.2gis.ru/api/v3/projects/2997/trigger/builds"
  dependencies: []
  tags: [ io, docker-engine ]

deploy:relizard:review:
  stage: deploy
  when: manual
  variables:
    GIT_STRATEGY: none
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    url: http://vstore-env-${CI_COMMIT_REF_SLUG}.web-staging.2gis.ru/swagger
    on_stop: destroy:relizard:stop-review
  only:
    - branches
  except:
    - master
  script:
    - 'export GECKO_PAYLOAD="{\"branch\":\"env/${CI_COMMIT_REF_SLUG}\",\"versions\":{\"vstore\":\"${CI_TAG}\"}}"'
    - 'curl -s -X POST http://relizard-gecko.web-staging.2gis.ru/envs -H "content-type: application/json" -d $GECKO_PAYLOAD --trace-ascii ${CI_PROJECT_DIR}/gecko_trace'
    - '_poll="curl -s -X GET http://relizard-gecko.web-staging.2gis.ru/envs/env/${CI_COMMIT_REF_SLUG}"'
    - 'export _elapsed=0'
    - 'echo ${CI_COMMIT_REF_SLUG:0:20} | sed -r "s/^(ams-[0-9]*)(.*)/\1/" | xargs -i printf "Environment will be ready on address:\n\033[0;32mhttp://vstore-env-{}.web-staging.2gis.ru/swagger\033[0m\n"'
    - 'while true; do sleep 5; let _elapsed=_elapsed+5; _status=$(${_poll} | python -c "import sys, json; print json.load(sys.stdin)[\"status\"]"); echo "Elapsed ${_elapsed}s, status: ${_status}"; case $_status in running) continue;; pending) continue;; success) exit 0;; *) exit 99;; esac; done'
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_SHA}"
    expire_in: '1 week'
    paths:
      - ${CI_PROJECT_DIR}/gecko_trace
  dependencies: []
  tags: [ io, docker-engine ]

destroy:relizard:stop-review:
  stage: deploy
  when: manual
  variables:
    GIT_STRATEGY: none
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    action: stop
  only:
    - branches
  except:
    - master
  script:
    - curl -s -X DELETE http://relizard-gecko.web-staging.2gis.ru/envs/env/${CI_COMMIT_REF_SLUG}
  dependencies: []
  tags: [ io, docker-engine ]

# ================= End =================

cleanup:registry:
  stage: end
  when: always
  variables:
    GIT_STRATEGY: none
    TAG_MASK: "branch-"
    IMAGE_LIFE_TIME_DAYS: "7"
  script:
    - hub-tool tags:cleanup --regexp "$TAG_MASK*" --days $IMAGE_LIFE_TIME_DAYS --path ams/vstore
    - hub-tool tags:cleanup --regexp "$TAG_MASK*" --days $IMAGE_LIFE_TIME_DAYS --path ams/vstore-worker
    - hub-tool tags:cleanup --regexp "$TAG_MASK*" --days $IMAGE_LIFE_TIME_DAYS --path ams/vstore-renderer
    - hub-tool tags:cleanup --regexp "$TAG_MASK*" --days $IMAGE_LIFE_TIME_DAYS --path ams/cloning-tool
  dependencies: []
  tags: [ docker-engine, io ]
